image: docker:18


# cache node_modules directory
cache:
  key: "$CI_BUILD_REF_NAME node:10.16.3-alpine"
  paths:
  - node_modules/



stages:
  - build
  - push



# before_script:
  # - docker info


# this stage will compile the Angular client, 
build:
  stage: build
  script:
    - docker build -t zentiment-client:latest .
    - docker run -dPi zentiment-client:latest
    - docker push dvdgege5/zentiment:latest
  tags:
    - docker



# this stage pushes the necessary containers to production server
push:
  stage: push
  script:
    - pwd
    - docker pull dvdgege5/zentiment:latest
