image: docker:18


stages:
  - build
  - push



before_script:
  - docker info


# this stage will compile the Angular client, 
build:
  stage: build
  script:
    - docker build -t zentiment-client .
    - docker run -dPi zentiment-client
  tags:
    - docker


push:
  stage: push
  script:
    - pwd
