image: docker:18


# cache node_modules directory
cache:
  key: "$CI_BUILD_REF_NAME node:10.16.3-alpine"
  paths:
  - node_modules/



stages:
  - build
  - push



# before_script:
  # - docker info


# this stage will compile the Angular client, 
build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/davidliugit/zentiment .
    - docker push registry.gitlab.com/davidliugit/zentiment
  tags:
    - docker



# this stage pushes the necessary containers to server
push:
  stage: push
  script:
    - ssh allah@159.89.182.50
    - docker pull registry.gitlab.com/davidliugit/zentiment
    - hostname
